version: '3.8'

services:
  app:
    build: .
    container_name: "time_tracker_codebase"

    environment:
      - ENV=${ENV}
      - SERVER_PORT=${SERVER_PORT}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_URI=mongodb://${MONGO_HOST}:${MONGO_PORT}
    volumes:
      - .:/app
    ports:
      - "3000:${SERVER_PORT}"

  mongodb:
    image: mongo
    container_name: "time_tracker_DB"
    restart: always
    ports:
      - "27017:27017"
